services:
  app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - seed_vol:/data
      - cron_vol:/cron
      # Mount keys (Read Only)
      - ./student_private.pem:/app/student_private.pem:ro
      - ./student_public.pem:/app/student_public.pem:ro
    environment:
      - TZ=UTC

volumes:
  seed_vol:
  cron_vol: